### ISSUE TITLE
Use selectize as in newest Administrate

### ISSUE THREAD

**Issue by benoror** [XPBytes/administrate-field-scoped_has_many#4]
Would like to use `selectize` as newer versions of Administrate do: https://github.com/thoughtbot/administrate/search?q=selectize

Might be a matter of supporting it to be loaded with the JS: https://github.com/thoughtbot/administrate/issues/585

Any hints would be greatly appreciated!

<img width="929" alt="Screen Shot 2022-09-21 at 23 16 16" src="https://user-images.githubusercontent.com/119117/191657452-3b6c2f59-6748-4e48-9a7e-ea5c38cd008a.png">

VS

<img width="898" alt="Screen Shot 2022-09-21 at 23 16 43" src="https://user-images.githubusercontent.com/119117/191657459-24fc41bc-9830-4ce4-ab28-999e9d07c7b7.png">

**Comment by benoror** [comment]
Ended up in going back to `Field::HasMany` and scoping using this approach: 

- https://github.com/thoughtbot/administrate/blob/main/docs/guides/scoping_has_many_relations.md
- https://stackoverflow.com/questions/59059701/rails-administrate-customize-has-many

**Comment by keithlayne** [comment]
The reason that it doesn't use selectize, even though it uses administrate's `has_many/_form.html.erb`, is because administrate's JS does this:

```js
$(function() {
  $('.field-unit--belongs-to select').selectize({});
  $(".field-unit--has-many select").selectize({});
  $('.field-unit--polymorphic select').selectize({});
});
```

(at least in the version I'm still on, 0.18.0)

The field generates a different class, so you'd need this to happen in JS somewhere:

```js
$('.field-unit--scoped-has-many select').selectize({});
```
